import "~/styles/globals.css"

import { GeistSans } from "geist/font/sans"
import { type Metadata } from "next"
import Link from 'next/link'

import { ClerkProvider } from "@clerk/nextjs"
import TopNav from './_components/topnav';

export const metadata: Metadata = {
  title: "T3 Gallery",
  description: "Generated by a loyal subscriber to theo on youtube",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body>
          <TopNav />
          {children}
        </body>
      </html>
    </ClerkProvider>   
  )
}
