import "~/styles/globals.css"

import { GeistSans } from "geist/font/sans"
import { type Metadata } from "next"
import Link from 'next/link'

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

function TopNav() {
  return (
    <nav className="bg-gray-800 p-4">
      <ul className="flex justify-between space-x-4 font-semibold">
        <li>
          <Link href="/">Gallery</Link>
        </li>
        <li>
          <Link href="/about">Sign in</Link>
        </li>
      </ul>
    </nav>
  )
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TopNav />
        {children}
      </body>
    </html>
  )
}
