import "~/styles/globals.css"

import { GeistSans } from "geist/font/sans"
import { type Metadata } from "next"
import Link from 'next/link'
import "@uploadthing/react/styles.css";

import { ClerkProvider } from "@clerk/nextjs"
import TopNav from './_components/topnav';
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin"
import { extractRouterConfig } from "uploadthing/server"
import { ourFileRouter } from "./api/uploadthing/core"

export const metadata: Metadata = {
  title: "T3 Gallery",
  description: "Generated by a loyal subscriber to theo on youtube",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body>
        <NextSSRPlugin
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
          <TopNav />
          {children}
        </body>
      </html>
    </ClerkProvider>   
  )
}
